name: Docker Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Convert repository name to lowercase
        run: |
          echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
        
      - name: Build and push Blog
        uses: docker/build-push-action@v4
        with:
          context: ./Blog
          push: true
          tags: ghcr.io/${{ env.REPO_LOWER }}/blog:latest
          
      - name: Build and push Admin
        uses: docker/build-push-action@v4
        with:
          context: ./Admin
          push: true
          tags: ghcr.io/${{ env.REPO_LOWER }}/admin:latest
          
      - name: Build and push Service
        uses: docker/build-push-action@v4
        with:
          context: ./Service
          push: true
          tags: ghcr.io/${{ env.REPO_LOWER }}/service:latest 