name: Docker Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Blog
        uses: docker/build-push-action@v4
        with:
          context: ./Blog
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/thrivex-blog:latest
          
      - name: Build and push Admin
        uses: docker/build-push-action@v4
        with:
          context: ./Admin
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/thrivex-admin:latest
          
      - name: Build and push Service
        uses: docker/build-push-action@v4
        with:
          context: ./Service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/thrivex-service:latest 